# Generated by Django 4.1 on 2022-08-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(editable=False, max_length=100)),
                ('email', models.EmailField(editable=False, max_length=100)),
                ('content', models.TextField(editable=False, max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='blog.review'),
        ),
    ]
