# Generated by Django 4.1 on 2022-08-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_review_content_alter_review_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='blog.tag'),
        ),
        migrations.AddField(
            model_name='blog',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews', to='blog.review'),
        ),
    ]
