# Generated by Django 4.1 on 2022-08-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_reviews_alter_blog_tags_blog_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='blog.review'),
        ),
    ]
